name: xEssentials
version: ${project.version}
description: core system
author: Xeph0re
authors: [] 
website:

main: tv.mineinthebox.essentials.xEssentials
database: false
depend: []
softdepend: [ManCo, Vault, WorldEdit, WorldGuard, LWC]
loadbefore: [Towny]

commands:
  home:
     description: allows you to use the home command
     aliases: []
  sethome:
     description: allows you to set your home
     aliases: []
  gamemode:
     description: allows you to set your gamemode
     aliases: [gm]
  setspawn:
     description: allows you to set spawn
     aliases: []
  spawn:
     description: teleports to spawn
     aliases: []
  teleport:
     description: allows you to teleport
     aliases: [tp]
  vanish:
     description: allows you to vanish yourself
     aliases: [v]
  invsee:
     description: see a inventory of a player
     aliases: []
  torch:
     description: toggles torch
     aliases: []
  spawnmob:
     description: spawn a mob
     aliases: []
  firefly:
     description: toggles firefly
     aliases: []
  fly:
     description: toggles fly
     aliases: []
  modreq:
     description: create a modreq
     aliases: []
  check:
     description: check all your modreqs
     aliases: []
  done:
     description: done a modreq
     aliases: []
  claim:
     description: claim a modreq
     aliases: []
  xEssentials:
     description: xEssentials
     aliases: []
  ban:
     description: ban a player
     aliases: []
  tempban:
     description: tempban a player
     aliases: [tb]
  unban:
     description: unban a player
     aliases: [pardon]
  mute:
     description: mute a player
     aliases: []
  unmute:
     description: unmute a player
     aliases: []
  tphere:
     description: tphere a player
     aliases: []
  tpa:
     description: sent a tpa request to a player
     aliases: []
  tpaccept:
     description: accept a tpa!
     aliases: []
  tpdeny:
     description: deny a tpa!
     aliases: []
  list:
     description: shows a list of all online players
     aliases: []
  afk:
     description: set your to afk
     aliases: []
  homeinvite:
     description: home invites
     aliases: [hi]
  more:
     description: clones the item in your hand
     aliases: []
  smite:
     description: smite a player
     aliases: []
  explode:
     description: explode a player
     aliases: []
  potato:
     description: change a player to a potato
     aliases: []
  back:
     description: teleport back to your last location
     aliases: []
  boom:
     description: launch a player in the sky!
     aliases: []
  spawner:
     description: change spawners
     aliases: []
  speed:
     description: change your walk speed
     aliases: []
  hand:
     description: check the item in your hand
     aliases: []
  task:
     description: do a task
     aliases: []
  powertool:
     description: activate a powertool
     aliases: [pt]
  nuke:
     description: activates a nuke
     aliases: []
  fakenuke:
     description: activates a fake nuke
     aliases: []
  compass:
     description: activates the compass following
     aliases: []
  hat:
     description: use items as hat
     aliases: []
  herobrine:
     description: summon a Herobrine
     aliases: [hb]
  greylist:
     description: greylist management
     aliases: [gl]
  menu:
     description: shows admin menu
     aliases: [m]
  rules:
     description: shows all the rules
     aliases: [m]
  broadcast:
     description: show configuration of broadcasts
     aliases: [bc]
  give:
     description: give items to players
     aliases: []
  tp-id:
     description: use tp-id for modreqs
     aliases: []
  silence:
     description: silence your chat
     aliases: []
  ignore:
     description: ignore players
     aliases: []
  freeze:
     description: freeze a player
     aliases: []
  trollmode:
     description: troll a player by sitting on his head
     aliases: [troll]
  commandrestrict:
     description: restrict a command of a player
     aliases: [restrict]
  playerinfo:
     description: shows the player info of a player
     aliases: [info]
  kit:
     description: get a kit
     aliases: []
  kits:
     description: shows a list of kits
     aliases: []
  warp:
     description: warp to a location
     aliases: []
  setwarp:
     description: setwarp to a location
     aliases: []
  delwarp:
     description: delete a warp
     aliases: []
  warps:
     description: shows a list of all warps
     aliases: []
  wild:
     description: teleport to the wild!
     aliases: []
  money:
     description: economy money command
     aliases: [bal]
  cprivate:
     description: allows you to select a block to make it private
     aliases: []
  cremove:
     description: allows you to remove a block protection to make it public
     aliases: []
  cmodify:
     description: modify a protected block
     aliases: []
  portals:
     description: portal and multi world management
     aliases: [portal, mvp]
  arrow:
     description: a arrow machine gun
     aliases: []
  test:
     description: a arrow machine gun
     aliases: []
  spleef:
     description: the spleef minigame command!
     aliases: []
  lookup:
     description: look a player up whenever they are banned or not
     aliases: []
  proc:
     description: proc
     aliases: []
  kill:
     description: kills someone
     aliases: []
  backpack:
     description: gives backpacks
     aliases: []
  trollblock:
     description: change blocks into paranoid troll blocks
     aliases: []
  knock:
     description: enables or disables anti knockback
     aliases: []
  clear:
     description: clear a inventory
     aliases: []
  fire:
     description: set a player on fire
     aliases: []
  doublejump:
     description: allows a player to double jump
     aliases: []
  nick:
     description: changes a player name
     aliases: [nickname]
  spectate:
     description: spectate a player
     aliases: []
  editsign:
     description: edit a sign
     aliases: [es]
  drunk:
     description: talk drunk and derpish
     aliases: [derp]
  spawnerblock:
     description: creates a tempory spawner
     aliases: [sb]
  floor:
     description: makes a floor like a fast place!
     aliases: [fl]
  wall:
     description: makes a wall like a fast place!
     aliases: [wl]
  nether:
     description: teleport to the nether on exact coords
     aliases: []
  getchunkfile:
     description: finds the chunk as a file
     aliases: [findchunk, chunkfinder]
  tennis:
     description: starts a minigame called chickentennis
     aliases: [chickentennis]
  football:
     description: starts a minigame called slimefootball
     aliases: [slimefootball]
  parkour:
     description: allows you to join or create parkour minigames
     aliases: []